### PR TITLE
Remove unclear licensed fixedsys font

### PR DESCRIPTION
**Pull request by falkTX**
The "fixedsys.ttf" font file does not have a clear license, seems a very old font that got some used by microsoft at some point.
But I couldn't find details on allowed uses, redistribution, derivatives, etc.
As such, it is unsuitable for use in a GPL licensed project.
It also complicates packaging.

This font is never used in the code though, as the C++ classes that reference it are defined but never used.
So I replaced it with the monospaced font provided by VCV Rack, just so it still works in case these classes are later on used in some new modules.

### CODE REVIEW

**Comment by hires** [comment]
It's some old font I found somewhere and I use it in some other plugins that use the same libs. I'm pretty sure it's so generic that nobody is going to care about it, especially if it's not used in this project.

**Comment by falkTX** [comment]
That doesnt fix the license situation, you can ignore it but the issue is still there.
You are using a font you have no rights to. And anyway there are many other monospaced fonts we can use, why insist on this one?

**Comment by dromer** [comment]
@hires if it's not used then why not just remove this and the code related to it?

**Comment by hires** [comment]
@dromer It's used in other code I use for non-public plugins. I like that 8 bit look! So changing it to a regular monospaced font is not really a suitable option.

I'll dig around for something similar or try to find where I got that one... in the meantime chill... nobody is going to die if this stays in there a bit longer.

**Comment by falkTX** [comment]
It is fine to take your time, just please dont close the ticket and try to hide the issue. Thanks.

**Comment by hires** [comment]
Okay, I've opened it again. But please don't tell me what to do. It's my project.

**Comment by dromer** [comment]
@hires we're not telling you what to do, just want to protect your project from any liability.

And because your project is FOSS it also has consequences for any downstream projects that may use it.

I hope you find a suitable replacement :)

**Comment by hires** [comment]
Will look into it. Sorry for my sour tone but I'm totally burned out and on a Friday evening this is the last thing I want to think about. I'll look for a reasonable facsimile when I have some moments.

**Comment by falkTX** [comment]
Hi there. Just noticed the commit bbe023843a490ff81fbde482c3ec641c7c36c50a which you mention:

> All panel designs, graphics, logos and other media files are copyright Andrew Kilpatrick and/or others and may not be used, forked or redistributed without permission

The right to fork is an essential github action, you cannot forbid it as it goes against the [GitHub ToS](https://docs.github.com/en/github/site-policy/github-terms-of-service#5-license-grant-to-other-users)

> By setting your repositories to be viewed publicly, you agree to allow others to view and "fork" your repositories (this means that others may make their own copies of Content from your repositories in repositories they control)

I don't quite get it tbh, either something is opensource/free-software or it is not.
Trying to forbid redistribution goes against everything that opensource stands for...

Can you clarify what is your intention here? Thank you

**Comment by hires** [comment]
This is pretty common practice in VCV Rack modules, where they are open source (for learning / reusing the code) but contain artwork and branding that is specific to the creator. I don't really see how what I'm doing is any different than probably thousands of brands who allow free use of their code but prohibit the impersonation of their company / brand by restricting use of logos and other graphics.

Anyway, I'm still looking for a replacement font so I'll leave this open.

**Comment by falkTX** [comment]
You can simply use one of the many available creative-commons licenses that describe the situation better than trying to do it by ourselves. Trademark and brand protection has nothing to do with it though, compared to the code it is yours but still opensource and able to be redistributed, recompiled, modified, sold etc. Trying to do things against that is a little weird when it comes to opensource that is all.

In my opinion VCV is quite the terrible example for this.. making artwork have CC non-derivative clause but at the same time have it include VCV branding which cannot be used in derivatives. Which basically forbids any project based on VCVRack from using the base/core, Fundamental and all other panels. This is clearly against the ideas of the [free culture movement](https://en.wikipedia.org/wiki/Free-culture_movement).

**Comment by falkTX** [comment]
Well great news, fixedsys seems to have gone public domain. see https://github.com/kika/fixedsys

**Comment by dromer** [comment]
@falkTX you can close this pr then ;)

**Comment by falkTX** [comment]
not quite. we need to check if the ttf matches the "new" public domain release. the old font was not generated while opensource

**Comment by dromer** [comment]
> not quite. we need to check if the ttf matches the "new" public domain release. the old font was not generated while opensource

I had a try at this using `font-tools` and `ttx` and so far haven't been able to set the exact same character-set as the current ttf file uses so couldn't get the same file. However building the entire ttf is doable (need to use the currently open fix https://github.com/kika/fixedsys/pull/30 on my system). The resulting file is about ~20x bigger than what we have now though, so we should perhaps want to trim for any chars not needed.

**Comment by falkTX** [comment]
@hires Just replaced the fixedsys with its public domain variant. It is a little bigger, because it supports many more languages and ligatures, but will look alike and now have proper licensing.

Would be great to make the artwork rules more permissive though, otherwise we are not officially allowed to even clone the repo for local builds..
Even taking what VCV does for Fundamental https://github.com/VCVRack/Fundamental/blob/v2/LICENSE.md would be better, at least that one allows redistribution and local use.

**Comment by hires** [comment]
I have found and replaced fixedsys.ttf with one that has an open license and added info about it in an accompanying file.

**Comment by dromer** [comment]
Why did you rename the new font to the old (proprietary) name? this will likely just confuse anyone using the project.

**Comment by hires** [comment]
> Why did you rename the new font to the old (proprietary) name? this will likely just confuse anyone using the project.

Many of my plugins use the original file so I wanted to modify it "upstream" as it were. The accompanying text file explains the origin of the file so there shouldn't be any confusion.

**Pull request closed without merging**
